    - name: Install Python Flask dependencies
      pip:
        name: '{{ item }}'
        state: present
      with_items:
       - flask
       - flask-mysql

    - name: Copy web-server code
      copy: src=application.py dest=/home/ansadmin/python-flask-aws-beanstalk/application.py

    - name: Start web-application
      shell: FLASK_APP=/home/ansadmin/python-flask-aws-beanstalk/application.py nohup flask run --host=0.0.0.0 &


      