    - name: Install dependencies
      apt: name={{ item }} state=present
      with_items:
       - python3
       - python3-setuptools
       - python3-dev
       - python3-pip
       - python3-mysqldb